version: '3'
services:
  sqlite:
    image: nouchka/sqlite3
    container_name: sqlite_service
    volumes:
      - ./data:/db
    working_dir: /db
    stdin_open: true
    tty: true
    platform: linux/amd64
